<?php

/**
 * @file
 *
 * Hooks and callbacks for this module.
 */
function islandora_google_pdfreader_menu() {
  $items = array();
  $items['admin/islandora/google_pdfreader'] = array(
    'title' => 'Google Pdf Reader',
    'description' => 'Configure the Islandora Google Pdf Reader module.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('islandora_google_pdfreader_admin'),
    'file' => 'includes/admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['islandora/object/%islandora_object/googlepdfreader'] = array(
    'weight' => -3,
    'title' => 'Read',
    'page callback' => 'islandora_google_pdfreader_view',
    'page arguments' => array(2),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'islandora_google_pdfreader_access',
    'access arguments' => array(2),
  );

  return $items;
}

/**
 * determines whether or not to show this modules tab
 * @global object $user
 * @param FedoraObject $fedora_object
 * @return boolean
 */
function islandora_google_pdfreader_access($fedora_object) {
  if (!isset($fedora_object)) {
    return FALSE;
  }
  $models = $fedora_object->models;
  $cmodel_list = array_keys(variable_get('islandora_google_pdfreader_mappings', array()));
  $same = array_intersect($cmodel_list, $models);
  if (count($same) > 0 && $fedora_object->getDatastream("PDF")) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Theme registry function
 *
 *  @return array
 */
function islandora_google_pdfreader_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_google_pdfreader_view' => array(
      'template' => 'theme/islandora-google-pdfreader',
      'variables' => array('islandora_objects' => NULL),
    ),
    'islandora_google_pdfreader_admin_table' => array(
      'render element' => 'form',
    ),
  );
}

/**
 * the google pdf reader view
 *
 * @param FedoraObject $object
 * @return string
 */
function islandora_google_pdfreader_view($object) {
  $output = theme('islandora_google_pdfreader_view', array('islandora_object' => $object));
  return $output;
}

/**
 * preprocess hook
 * @param array $variables
 */
function islandora_google_pdfreader_preprocess_islandora_google_pdfreader_view(&$variables) {
  $islandora_object = $variables['islandora_object'];
  $arr = variable_get('islandora_google_pdfreader_mappings', array());
  $models = $islandora_object->models;
  $dsid = NULL;
  //TODO we may want to load a list of cmodels specified in an admin
  //interface
  $cmodel_list = variable_get('islandora_google_pdfreader_mappings', array());
  foreach ($models as $model) {
    if (isset($cmodel_list[$model])) {
      $dsid = $cmodel_list[$model]['DSID'];
    }
  }
  $pid = $islandora_object->id;
  $label = $islandora_object->label;
  if (!empty($label)) {
    drupal_set_title($label);
  }
  $variables['viewer_url'] = 'http://docs.google.com/viewer?url=' . url("islandora/object/{$pid}/datastream/$dsid/download", array('absolute' => TRUE)) . '&embedded=TRUE';

  $anonymous_account = user_load(0); //get the anonymous user
  //we only want to show the Google viewer if anonymous can get to the pdf as google reader
  //will be hitting the url unauthenticated
  $variables['show_viewer'] = FALSE;
  if (user_access(FEDORA_VIEW_OBJECTS, $anonymous_account)) {
    $variables['show_viewer'] = TRUE;
  }

  global $base_url;
  require_once(DRUPAL_ROOT .'/sites/all/modules/islandora/includes/datastream.inc');
  $islandora_object = $variables['islandora_object'];
  $variables['pdf_download_path'] = '../../../' . (islandora_datastream_get_url($islandora_object->getDatastream("PDF"), 'download'));
  $variables['pdf_download_image'] = $base_url . '/' . drupal_get_path('module', 'islandora_google_pdfreader') . '/images/pdf_download.png';
}