<?php

/**
 * @file
 * Hooks and callbacks for this module.
 */

/**
 * Implements hook_menu.
 *
 * @return array
 *   the menu array
 */
function islandora_google_pdfreader_menu() {
  $items = array();
  $items['admin/islandora/google_pdfreader'] = array(
    'title' => 'Google Pdf Reader',
    'description' => 'Configure the Islandora Google Pdf Reader module.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('islandora_google_pdfreader_admin'),
    'file' => 'includes/admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['islandora/object/%islandora_object/googlepdfreader'] = array(
    'weight' => -3,
    'title' => 'Read',
    'page callback' => 'islandora_google_pdfreader_view',
    'page arguments' => array(2),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'islandora_google_pdfreader_access',
    'access arguments' => array(2),
  );

  return $items;
}

/**
 * Determines whether or not to show this modules tab.
 *
 * @global object $user
 *
 * @param FedoraObject $fedora_object
 *   The fedora object we are viewing
 *
 * @return bool
 *   TRUE if we have permission to view and the object has the expected datastream
 */
function islandora_google_pdfreader_access($fedora_object) {
  if (!isset($fedora_object)) {
    return FALSE;
  }
  $models = $fedora_object->models;
  $cmodel_list = variable_get('islandora_google_pdfreader_mappings', array());

  $dsid = NULL;
  foreach ($models as $model) {
    if (isset($cmodel_list[$model])) {
      $dsid = $cmodel_list[$model]['DSID'];
    }
  }
  $cmodel_list = array_keys($cmodel_list);
  $same = array_intersect($cmodel_list, $models);
  if (count($same) > 0 && isset($fedora_object[$dsid])) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Theme registry function.
 *
 * @return array
 *   theme functions
 */
function islandora_google_pdfreader_theme() {
  return array(
    'islandora_google_pdfreader_view' => array(
      'template' => 'theme/islandora-google-pdfreader',
      'variables' => array('islandora_objects' => NULL),
    ),
    'islandora_google_pdfreader_admin_table' => array(
      'render element' => 'form',
    ),
  );
}

/**
 * The google pdf reader view.
 *
 * @param FedoraObject $object
 *   The object we are viewing
 *
 * @return string
 *   html
 */
function islandora_google_pdfreader_view($object) {
  $output = theme('islandora_google_pdfreader_view', array('islandora_object' => $object));
  return $output;
}

/**
 * Preprocess hook.
 *
 * @param array $variables
 *   theme variables array
 */
function islandora_google_pdfreader_preprocess_islandora_google_pdfreader_view(&$variables) {
  $islandora_object = $variables['islandora_object'];
  $arr = variable_get('islandora_google_pdfreader_mappings', array());
  $models = $islandora_object->models;
  $dsid = NULL;
  $cmodel_list = variable_get('islandora_google_pdfreader_mappings', array());
  foreach ($models as $model) {
    if (isset($cmodel_list[$model])) {
      $dsid = $cmodel_list[$model]['DSID'];
    }
  }
  $pid = $islandora_object->id;
  $label = $islandora_object->label;
  if (!empty($label)) {
    drupal_set_title($label);
  }
  $variables['viewer_url'] = 'http://docs.google.com/viewer?url=' . url("islandora/object/{$pid}/datastream/$dsid/download", array('absolute' => TRUE)) . '&embedded=TRUE';

  $anonymous_account = user_load(0);
  $variables['show_viewer'] = FALSE;
  if (user_access(FEDORA_VIEW_OBJECTS, $anonymous_account)) {
    $variables['show_viewer'] = TRUE;
  }

  global $base_url;
  module_load_include('inc', 'islandora', 'includes/datastream');
  $variables['pdf_download_path'] = url(islandora_datastream_get_url($islandora_object->getDatastream($dsid), 'download'));
  $variables['pdf_download_image'] = $base_url . '/' . drupal_get_path('module', 'islandora_google_pdfreader') . '/images/pdf_download.png';
}